config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :recipes
  resources :dashboard
  root to: "home#index"

  post 'recipes/query_forma' =>'recipes#forma'
  post 'recipes/query_formb' =>'recipes#formb'
  get 'recipes/querya/(:culture/:options)' =>'recipes#find_by_culture', as: :querya
  get 'recipes/queryb/(:name/:options)' =>'recipes#find_by_ingredients', as: :queryb
  get 'recipes/sort/:recipe/:sort_type/:current_state' =>'recipes#sort', as: :sort
  get 'surprise/' =>'recipes#surprise', as: :surprise
  get 'myfavorites/:id'=>'recipes#editFavorites', as: :edit_favorites
  get 'myfavorites/' =>'recipes#getFavorites', as: :myfavorites
  get 'recipes/' =>'recipes#index'

 

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :ingredients
	has_many :steps
	accepts_nested_attributes_for :ingredients, :allow_destroy => true
	accepts_nested_attributes_for :steps, :allow_destroy => true
	validates :name, presence: true


	def self.sort_by_specifics(array, type)
		case type
		when "skillUp"
		 	array.sort!  do |a, b| 
		 		case 
		 		when a.skill==b.skill 
		 			0 
		 		when a.skill =="Beginner"
		 			-1
		 		when (a.skill =="Intermediate" and b.skill=="Advance")
		 			-1
		 		when (a.skill=="Intermediate" and b.skill=="Beginner")
		 			1
		 		when a.skill=="Advance"
		 			1
		 		end
		 	end
		when "skillDown"
			array.sort!  do |a, b| 
		 		case 
		 		when a.skill==b.skill 
		 			0 
		 		when a.skill =="Beginner"
		 			1 
		 		when (a.skill =="Intermediate" and b.skill=="Advance")
		 			1
		 		when (a.skill=="Intermediate" and b.skill=="Beginner")
		 			-1
		 		when a.skill=="Advance"
		 			-1
		 		end
		 	end
		 		
		when "costUp"
			array.sort! { |x, y| x.cost <=> y.cost}
		when "costDown"
			array.sort! { |x, y| y.cost <=> x.cost}
		when "feedsUp"
			array.sort! { |x, y| x.feeds <=> y.feeds}
		when "feedsDown"
			array.sort! { |x, y| y.feeds <=> x.feeds}
		when "timeUp"
			array.sort! { |x, y| x.time <=> y.time}
		when "timeDown"
			array.sort! { |x, y| y.time <=> x.time}
		end

	end


end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  respond_to :html, :js
  # Added to restrict non-logged in individuals from adding recipes
  before_filter :authenticate_user!
  skip_before_filter :verify_authenticity_token, :only => [:create,:update]

	before_action :prepareOptions, only: [:new, :create, :show, :find_by_culture, :find_by_ingredients,:index,:sort, :edit,:update]
  def index
    @recipes = Recipe.order(favCount: :desc).all
    @sort_type="favs"
    @current_state= "Down"
  
  end

  def prepareOptions
  	@meat = ["Beef", "Chicken", "Pork", "Tofu", "Turkey", "Eggs"]
  	@vegetables = ["Artchoke Hearts", "Broccoli", "Carrot", "Corn", "Peas", "Spinach", "Tomato","Green Onions","Cucumber"]
  	@spices= ["Salt", "Pepper", "Tumeric", "Whole Garlic", "Garlic Powder"]
    @misc= ["Cheese", "Cream", "Oil", "Pasta", "Sauce", "Wine", "Herbs", "Rice", "Citrus"]
  	@cultures = ["American", "Chinese", "Greek", "Indian", "Italian", "Japanese", "Kosher", "Mexican", "Thai"]
  	@options = ["Nut Free", "Veg Friendly", "Gluten Free", "Shellfish"]
  	@main_option = ["Meat","Vegetables", "Spice", "Misc" ]
  	@meat_serving = ["pieces", "oz", "pounds","whole"]
  	@veg_serving = ["cups", "cloves", "ounces", "tablespoons", "teaspoons","whole", "pieces","pinch"]
    @choices = {"main"=>@meat, "veg"=>@vegetables, "spice"=>@spices, "misc"=>@misc}
    @servings = {"main"=>@meat_serving, "veg"=>@veg_serving, "spice"=>@veg_serving, "misc"=>@veg_serving,"none"=>(@veg_serving+@meat_serving)}
  end

  def new
  	@recipe = Recipe.new
  	@recipe.steps.build
    @recipe.culture=""
    @recipe.options=""
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice]="Recipe Deleted!"
    redirect_to recipes_path
  end

  def update
    @recipe = Recipe.find(params[:id])
    if params[:culture]
      culture_keywords = params[:culture]
      @recipe.culture = (culture_keywords.join(","))
    else
      @recipe.culture=""
    end
    if params[:options]
      options_keywords = params[:options]
      @recipe.options = options_keywords.join(",")
    else
      @recipe.options=""
    end
    if params[:add_step]
        puts "add step called"
        # add empty step associated with @recipe
        @recipe.steps.build
    elsif params[:Main]
      @recipe.ingredients.build(:ing_type=>'main')
    elsif params[:Veg]
      @recipe.ingredients.build(:ing_type=>'veg')
    elsif params[:Spice]
      @recipe.ingredients.build(:ing_type=>'spice')
    elsif params[:Misc]
      @recipe.ingredients.build(:ing_type=>'misc')
    elsif params[:FreeForm]
      @recipe.ingredients.build(:ing_type=>"none")
    else
      if @recipe.culture==""
        puts "in culutre if"
        flash[:notice] = "Please select a culture."
        render action: 'edit'
        return
      end
     
      if params[:steps].blank? and @recipe.steps.blank?
        puts "steps if"
        flash[:notice]="Please include at least one step"
        render action: 'edit'
        return
      end
      if params[:ingredients].blank? and @recipe.ingredients.blank?
        puts "ingredient check"
        flash[:notice]="Please include at least one  ingredient"
        render action: 'edit'
        return
      end 

      if @recipe.source==""
        flash[:notice]="Who is the source?"
        render action: 'edit'
        return
      end

      if @recipe.update(recipe_params)
        check_ingredients(@recipe.ingredients).each do |bad_ing|
          @recipe.ingredients.destroy(bad_ing)
        end
        check_steps(@recipe.steps).each do |bad_step|
          @recipe.steps.destroy(bad_step)
        end
        redirect_to @recipe and return
      else
        render 'edit'
      end
    end
    puts "made it to end"
    render :action => 'edit'

  end

  def edit
    @recipe = Recipe.find(params[:id])

  end
  	
  def forma
    respond_to do |format|
      if params[:culture]
        @cultures=params[:culture]
       
      else
          @cultures = "None"
      end
      if params[:options]
        @options=params[:options]
      else
        @options="None"
      end


      format.html{render :action=> :querya, :culture=>@cultures,:options=>@options}
      format.js{redirect_to querya_path(:culture=>@cultures, :options=>@options)}
    end

  end

  def formb
    respond_to do |format|
      puts params[:name]
      if params[:name]
        @names=params[:name]
      else
          @names = "None"
      end
      if params[:options]
        @options=params[:options]
      else
        @options="None"
      end
      format.html {redirect_to queryb_path(:name=>@names,:options=>@options) }
      format.js{redirect_to queryb_path(:name=>@names,:options=>@options)}
    end
  end

  def show
   
    @recipe = Recipe.find(params[:id])
  end

  def find_by_culture
    respond_to do |format|
      unless params[:culture]=="None"
     
        unless params[:options] =="None"
          @recipes = Recipe.order(favCount: :desc).where(:culture=>params[:culture].split("/")).where(:options=>params[:options])
        else
          @recipes = Recipe.order(favCount: :desc).where(:culture=>params[:culture].split("/"))
        end
      else
        unless params[:options] =="None"
          @recipes = Recipe.order(favCount: :desc).where(:options=>params[:options])
        else
          @recipes = Recipe.order(favCount: :desc).all
        end
      end
      @sort_type="favs"
      @current_state= "Down"
      format.html{render action: 'show_multiple'}
      format.js{render action: 'show_multiple'}
    end
  end

  def find_by_ingredients

    param = params[:name].split('/')
    if params[:name]=="None" and params[:options]=="None"
      @recipes = Recipe.order(favCount: :desc).all
    else
      @recipes=[]
      unless params[:options]=="None"
        options = params[:options].split('/')
        ids_2 = Recipe.order(favCout: :desc).where(:options=>params[:options]).pluck(:id)
      else
        culture=[]
        ids_2=Recipe.order(favCount: :desc).pluck(:id)
      end
      b = Hash.new(0)
      ids= Ingredient.where(:name=>param)
   
      ids.each do |v|
        #puts v.recipe_id, b[v.recipe_id]
        if ids_2.include? v.recipe_id
          b[v.recipe_id] += 1
        end
        
       # puts param.size
      end

      b.each do |key,array|
        integer = "#{key}".to_i
        if array >= param.size
           @recipes.push(Recipe.find(integer))
        end
      end
    end
    @sort_type="favs"
    @current_state= "Down"

    render 'show_multiple'
  end



  def create
    
  	@recipe = Recipe.new(recipe_params)
    puts @recipe.id
    if params[:culture]
      culture_keywords = params[:culture]
      @recipe.culture = (culture_keywords.join(","))
    else
      @recipe.culture=""
    end
    if params[:options]
      options_keywords = params[:options]
      @recipe.options = options_keywords.join(",")
    else
      @recipe.options=""
    end
    
  	if params[:add_step]
        puts "add step called"
      	# add empty step associated with @recipe
      	@recipe.steps.build
    elsif params[:Main]
      @recipe.ingredients.new(:ing_type=>'main')
    elsif params[:Veg]
      @recipe.ingredients.build(:ing_type=>'veg')
    elsif params[:Spice]
      @recipe.ingredients.build(:ing_type=>'spice')
    elsif params[:Misc]
      @recipe.ingredients.build(:ing_type=>'misc')
    elsif params[:FreeForm]
      @recipe.ingredients.build(:ing_type=>"none")
    else
      if @recipe.culture==""
        puts "in culutre if"
        flash[:notice] = "Please select a culture."
       render :action => 'new' and return
      end
      check_steps(@recipe.steps).each do |bad_step|
          @recipe.steps.delete(bad_step)
      end
      if params[:steps].blank? and @recipe.steps.blank?
        puts "steps if"
        flash[:notice]="Please include at least one step"
        render :action => 'new' and return
      end

      check_ingredients(@recipe.ingredients).each do |bad_ing|
        @recipe.ingredients.delete(bad_ing)
      end
      if params[:ingredients].blank? and @recipe.ingredients.blank?
        puts "ingredient check"
        flash[:notice]="Please include at least one  ingredient"
        render :action => 'new' and return
      end 

      if @recipe.source==""
        flash[:notice]="Who is the source?"
        render :action => 'new' and return
        
      end


      #Add @recipe.owner_id = something
      #if current_user
        @recipe.owner_id = current_user.id
      #else
      #  redirect_to new_user_session_path, notice: 'You are not logged in.'
      #end 

      if @recipe.save
        redirect_to @recipe and return
      end
      
      puts "check something"
    end
  
    puts "made it to the end"
    render :action => 'new'
   
  end

  def sort
    @recipes = Recipe.find(params[:recipe].split('/').map(&:to_i))
    puts params[:sort_type]+params[:current_state]
    @recipes=Recipe.sort_by_specifics(@recipes, params[:sort_type]+params[:current_state])
    @sort_type = params[:sort_type]
    if params[:current_state]=='Up'
      @current_state = "Down"
    else
      @current_state = "Up"
    end
    render action: 'show_multiple'
  end

  def surprise
    redirect_to Recipe.offset(rand(Recipe.count)).first

  end


  def editFavorites
    @recipe=Recipe.find(params[:id])
    if current_user.fav_recipes
      if current_user.fav_recipes.include? params[:id]
        if @recipe.favCount
          @recipe.favCount-=1
        else
          @recipe.favCount = 0
        end
    
        holder = current_user.fav_recipes.split(',').to_a
        holder.delete(params[:id])
        current_user.fav_recipes = holder.join(',')
        flash[:notice] = "Recipe Removed From Favorites"
      else
        if @recipe.favCount
          @recipe.favCount+=1
        else
          @recipe.favCount = 1
        end
        holder = current_user.fav_recipes.split(',').to_a
        holder.push(params[:id])

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipeDisplay.html.erb
<!--<hr>-->

<%if current_user.id==recipe.owner_id%>
	<%puts "something"%>
	<%=link_to "Edit", edit_recipe_path(recipe), class: "edit"%>
	<%=link_to "Delete", recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?' }, class: "delete"%>
<%end%>
<div style="text-align:center">
	<h2 style="text-align:center">
				 
	  <%= recipe.name %>
	</h2>
	 <div class="feedsContainer">
	  <h5 class="header" style="display:inline-block;">Feeds:</h5>
	  	<p>
	  		<%= recipe.feeds %>
		</p>
	</div>
	 <div class="timeContainer">
	  <h5 class="header" >Time:</h5>
	  	<p>
	  		<%= recipe.time %> Minutes
		</p>
	</div>

	<div class="costContainer" >

	  <h5 class="header">Cost:</h5>
	  <p>
	  	<%= recipe.cost %>
		</p>
	</div>


	<div class="skillContainer">


	  <h5 class="header">Skill Level:</h5>
	  <p>
	  <%= recipe.skill %>
	</p>
	</div>


</div>

<p id="general_pads" style="text-align:center">
  <strong class="header">Culture:</strong>
  <%= recipe.culture %>
</p>


<div class="ingredientContainer">
	<h5 class="header">Ingredients:</h5>
  	<ol>
	  <%recipe.ingredients.each do |ingredient| %>
	  	<li>
	  		<%=ingredient.quantity%>
	  		<%=ingredient.quantity_description%> of 
	  		<%=ingredient.name%> 
	  		<%=ingredient.description%>
	  	</li>
	  <%end%>
	</ol>
</div>

<div class="stepContainer">
  <h5 class="header">Steps:</h5>
  <ol>
  <%recipe.steps.each do |step| %>
  	<li><%=step.description%></li>
  <%end%>
 </ol>
</div>
<div id="general_pads" style="text-align:center">
	<strong class="header">Dietary Considerations:</strong>
	<p>
	  <%= recipe.options %>
	</p>
</div>
<hr>
<div class ="sourceContainer">
	 <%= recipe.source %>
   <!-- <%= recipe.owner_id %> this was a test -->
</div>
<%if current_user.fav_recipes%>
	<%if current_user.fav_recipes.include? recipe.id.to_s %>
		<%=link_to image_tag("Star_black.png"), edit_favorites_path(:id=>recipe.id)%>
	<%else%>
		<%=link_to image_tag("Star_white.png"), edit_favorites_path(:id=>recipe.id)%>
	<%end%>
<%else%>
	<%=link_to image_tag("Star_white.png"), edit_favorites_path(:id=>recipe.id)%>
<%end%>

app/views/recipes/_recipeLayout.html.erb
<div class="onoffswitch">
    <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked onchange="formChange(this)">
    <label class="onoffswitch-label" for="myonoffswitch">
        <span class="onoffswitch-inner"></span>
        <span class="onoffswitch-switch"></span>
    </label>
</div>



<div id="optionsa">
	<%= form_tag({controller: "recipes", action: "forma"}, remote: true ) do%>
		<h4>Select Culture:</h4>
		<div class="holder">
	 		<% @cultures.each do |o| %>
	  			<%file = image_path(o+".png")%>
	  			<div class="culture" style="display:inline-block; ">
 		 			<input name="culture[]" class="<%=o%>" type="checkbox" id="my<%=o%>" value="<%=o%>" onclick="$(this).submit();" >
	 		 		<label class="<%=o%>-label" for="my<%=o%>"></label>
	 		 		<p style="padding-left:7%;font-size:10px; text-align:center"><%=o%></p>
	 		 	</div>
	 		<%end%>
 		</div>
	 	<hr>
	 	<h4> Dietary Preferences</h4>
	 	<div class="holder">
			<% @options.each do |o| %>
				<span style="font-size:10px;"><%=o%></span>
	 		 	<input name="options[]" class="<%=o%>" type="checkbox" value="<%=o%>" onclick="$(this).submit();"/>
	 		<%end%>
	 	</div>

	 	<br>
		<% submit_tag("Find Me Recipes", class:"btn btn-success") %>
	<% end %>

	<p style="text-align:center">
	<%=link_to "Surprise Me", surprise_path(), class: "surpriseMe"%>
	</p>

</div>

<div id="optionsb" style="display:none">
	<%= form_tag({controller: "recipes", action: "formb"}, method: "post", remote: true) do%>

		<h4>Select Ingredients:</h4>
		<div class="holder">
		  	<% @meat.each do |o| %>
		  		<div class="culture" style="display:inline-block;">
		  			<%file = image_tag(o+".png", :height=>32)%>
	 		 		<input name="name[]" class="<%=o%>" id="my<%=o%>" type="checkbox" value="<%=o%>" onclick="$(this).submit();"/>
	 		 		<label class="<%=o%>-label" for="my<%=o%>"></label>
	 		 		<p style="padding-left:7%;font-size:10px;"><%=o%></p>
	 		 	</div>
	 		<%end%>
	 	</div>
		<hr>
 		<div class="holder">
	 		<% @misc.each do |o| %>
	 			<div style="display:inline-block;">
		  			<%file = image_tag(o+".png",:height=>32)%>
	 		 		<input name="name[]" class="<%=o%>" type="checkbox" id="my<%=o%>" value="<%=o%>" onclick="$(this).submit();" />
	 		 		<label class="<%=o%>-label" for="my<%=o%>"></label>
	 		 		<p style="font-size:10px;"><%=o%></p>
	 		 	</div>
	 		<%end%>
	 	</div>
	 	<hr>
 		<div class="holder">
	 		<% @vegetables.each do |o| %>
	 			<div style="display:inline-block">
		  			<%file = image_tag(o+".png",:height=>32)%>
	 		 		<input name="name[]" class="<%=o%>" id="my<%=o%>" type="checkbox" value="<%=o%>" onclick="$(this).submit();" /> 
	 		 		<label class="<%=o%>-label" for="my<%=o%>" ></label>
	 		 		<p style="font-size:10px;"><%=o%></p>
	 		 	</div>
	 		<%end%>
	 	</div>
	 	<hr>
	 	 <div class="holder">
 		<% @spices.each do |o| %>
  			<%file = image_tag(o+".png",:height=>32)%>
  			<span style="font-size:10px;"><%=o%></span>
		 		<input name="name[]" class="<%=o%>" type="checkbox" value="<%=o%>" onclick="$(this).submit();" />
 		<%end%>
		 </div>

	 	<hr>
	 		<h4> Dietary Preferences</h4>
	 	 <div class="holder">

			<% @options.each do |o| %>
				<span style="font-size:10px;"><%=o%></span>
			 		<input name="options[]" class="<%=o%>" type="checkbox" value="<%=o%>"  onclick="$(this).submit();"/>
	 		<%end%>
 		</div>

	 	<br>
		<% submit_tag("Find Me Recipes", class:"btn btn-success") %>
	<% end %>

	<p style="text-align:center">
	<%=link_to "Surprise Me", surprise_path(), class: "surpriseMe"%>
	</p>
	
</div>

app/views/recipes/_recipeSteps.html.erb
<ol>
	<%= f.fields_for :steps do |s| %>
		<li>
		<%=s.text_area :description,  {cols: 60, rows: 1,:onkeyup=>"textFieldAdjust(this)", class: "feedback-input-ingredients"}%>
		</li>
	<%end%>
</ol>

app/views/recipes/_show_multiple.html.erb
<%ids = []%>
<%recipes.each do |c|%>
	<%ids.push(c.id)%>
<%end%>

<div id="sort_bar">
	Sort by:
	<ul>
		<li><%=link_to "Skill", sort_path(:recipe=>ids, :sort_type=>"skill", :current_state=>@current_state), :remote => true, :onclick=>"resetCount()"%></a>
			<%if @sort_type=="skill" and @current_state == "Up"%>
				&#x2193;
			<%elsif @sort_type=="skill" and @current_state == "Down" %>
				&#x2191;
			<%end%>
		</li>
		<li><%=link_to "Cost", sort_path(:recipe=>ids, :sort_type=>"cost", :current_state=>@current_state), :remote => true, :onclick=>"resetCount()"%></a>
			<%if @sort_type=="cost" and @current_state == "Up"%>
				&#x2193;
			<%elsif @sort_type=="cost" and @current_state == "Down"%>
				&#x2191;
			<%end%>
		</li>
		<li><%=link_to "Feeds", sort_path(:recipe=>ids, :sort_type=>"feeds", :current_state=>@current_state), :remote => true, :onclick=>"resetCount()"%></a>
			<%if @sort_type=="feeds" and @current_state == "Up"%>
				&#x2193;
			<%elsif @sort_type=="feeds" and @current_state == "Down"%>
				&#x2191;
			<%end%>
		</li>
		<li><%=link_to "Time", sort_path(:recipe=>ids, :sort_type=>"time", :current_state=>@current_state), :remote => true, :onclick=>"resetCount()"%></a>
			<%if @sort_type=="time" and @current_state == "Up"%>
				&#x2193;
			<%elsif @sort_type=="time" and @current_state == "Down"%>
				&#x2191;
			<%end%>
		</li>
	</ul>
</div>
<div id="recipe">
	<% if recipes.size ==0%>
		<p class="btn-warning" style='text-align:center'>Sorry no recipes meet these parameters. Please Try Again</p>
	<%end%>
	<div id="message" class="btn-warning" style="display:none; text-align:center;">
		No more recipes fit this description
	</div>

	<%count = 1%>
	<% recipes.each do |recipe| %>
	
		<div id="recipe_<%=count%>" class="recipes"<%if count!= 1%>style="display:none"<%end%>>
			<%=render partial: "recipeDisplay", :locals=>{:recipe=>recipe}%>
		</div>
		<%count += 1%>
	<%end%>
</div>

<div id="button_pads">
	<button id="prev" class="btn btn-inverse" onclick="moveDown()">prev</button>
	<button id="next" class="btn btn-inverse" onclick="moveUp()">next</button>
</div>

<script>
	$(document).ready('ready()');
</script>

app/views/recipes/edit.html.erb
<%=stylesheet_link_tag "recipes"%>
<div id="recipe_page">
	<h1 style="text-align:center">New Recipe</h1>
	<% if flash[:notice] %>
	    <div class="notice"><%= flash[:notice] %></div>
	 <% end %>


	<div id="recipe_form">
		<%=render partial: "recipe_form", locals: {recipe: @recipe} %>
	</div>
</div>

app/views/recipes/edit.js.erb
$("#recipe_form").html("<%= escape_javascript(render partial: 'recipe_form', locals:{recipe: @recipe} ) %>");

app/views/recipes/getFavorites.html.erb
<%=stylesheet_link_tag "recipes"%>
<div id="recipe_page">
	<h2 style="text-align:center;"> My Favorite Recipes</h2>
	<div id="multiple_holder">
		<%= render partial: "show_multiple",  :locals=>{:recipes=>@recipes, :sort_type=> "time", :current_state=>@current_state}%>
	</div>

</div>

app/views/recipes/index.html.erb
<%=stylesheet_link_tag "recipes"%>
<div id="recipe_page">
	<h2 style="text-align:center;">Search For Recipes</h2>
	<div id="multiple_holder">
		<%= render partial: "show_multiple",  :locals=>{:recipes=>@recipes, :sort_type=> @sort_type, :current_state=>@current_state}%>

	</div>
	<div id="main">
		<%=render partial: "recipeLayout", locals: {} %>
	</div>
</div>

app/views/recipes/new.html.erb
<%= javascript_include_tag "application" %>	
<%=stylesheet_link_tag "recipes"%>
<div id="recipe_page">
	<h1 style="text-align:center">New Recipe</h1>
	<% if flash[:notice] %>
	    <div class="notice"><%= flash[:notice] %></div>
	 <% end %>


	<div id="recipe_form">
		<%=render partial: "recipe_form", locals: {recipe: @recipe} %>
	</div>
</div>

app/views/recipes/new.js.erb
$("#recipe_form").html("<%= escape_javascript(render partial: 'recipe_form', locals:{recipe: @recipe} ) %>");

app/views/recipes/show.html.erb
<%=stylesheet_link_tag "recipes"%>
<div id="multiple_holder">
  <div id="recipe">
    <%=render partial: "recipeDisplay", :locals=>{:recipe=>@recipe}%>
  </div>
  <div id="general_pads" style="position:absolute;left: 40%;width: 45%;">
    <%=link_to "Surprise Me", surprise_path(), class: "surpriseMe"%>
  </div>
</div>    

app/views/recipes/show_multiple.html.erb
<%=stylesheet_link_tag "recipes"%>
<div id="recipe_page">
	<h1> Search Recipes</h1>
	<div id="multiple_holder">
		<%= render partial: "show_multiple",  :locals=>{:recipes=>@recipes, :sort_type=> @sort_type, :current_state=>@current_state}%>
	</div>

	<%= render partial: "recipeLayout"%>

</div>

app/views/recipes/show_multiple.js.erb
$("#multiple_holder").html("<%= escape_javascript(render partial: 'show_multiple', locals:{recipes: @recipes, sort_type: @sort_type, current_state:@current_state} ) %>");
ready();