config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :recipes
  resources :dashboard
  root to: "home#index"

  post 'recipes/query_forma' =>'recipes#forma'
  post 'recipes/query_formb' =>'recipes#formb'
  get 'recipes/querya/(:culture/:options)' =>'recipes#find_by_culture', as: :querya
  get 'recipes/queryb/(:name/:options)' =>'recipes#find_by_ingredients', as: :queryb
  get 'recipes/sort/:recipe/:sort_type/:current_state' =>'recipes#sort', as: :sort
  get 'surprise/' =>'recipes#surprise', as: :surprise
  get 'myfavorites/:id'=>'recipes#editFavorites', as: :edit_favorites
  get 'myfavorites/' =>'recipes#getFavorites', as: :myfavorites
  get 'recipes/' =>'recipes#index'

 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<div id="container">
   <div id="header">
    <title>AroundTheTable</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
   </div>


   <div id="body">
      <div id="wrapper" class ="content">
        <%= csrf_meta_tags %>
        <nav class="navbar navbar-inverse" role="navigation">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
              <span class="sr-only">Toggle navigation</span>
            </button>
            <a class="navbar-brand" href="#" style="color:#1abc9c">Around The Table</a>
          </div>
          <div class="collapse navbar-collapse" id="navbar-collapse-01">
            <ul class="nav navbar-nav" style="display:inline-block;">
              <li><%= link_to "Dashboard", dashboard_index_path%></li>
                <li><%= link_to "My Profile", edit_user_registration_path%></li>
                <li><%= link_to "Add New Recipe", new_recipe_path%></li>
                <li><%= link_to "Search Recipes",  recipes_path()%>></li>
            </ul>
          
            <div id="user_nav" style="color:white" class="navbar-form navbar-right">
                <% if user_signed_in? %>
                  Logged in as <strong><%= current_user.email %></strong>.
                  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
                  <%= link_to "My Favorites", myfavorites_path, :class=>'navbar-link'%>
                <% else %>
                  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
                  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> 

                <% end %>
            </div>     
          </div><!-- /.navbar-collapse -->
        </nav><!-- /navbar -->

        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>

        <%= yield %>



        <div class="push"></div>

    </div>
   </div>

  <!--<div id="footer">
    <div id="footer_contents" class="btn-inverse" style="text-align:center">
        (c) Around the Table
    </div>
  </div>-->

</div>
</html>

app/views/layouts/recipe_layout.html.erb
<%=stylesheet_link_tag "recipes"%>

<!DOCTYPE html>
<html>
<head>
  <title>AroundTheTable</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>


  <nav class="navbar navbar-inverse" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <a class="navbar-brand" href="#" style="color:#1abc9c">Around The Table</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse-01">
      <ul class="nav navbar-nav" style="display:inline-block;">
        <li><%= link_to "Dashboard", dashboard_index_path%></li>
          <li><%= link_to "My Profile", edit_user_registration_path%></li>
          <li><%= link_to "Add New Recipe", new_recipe_path%></li>
          <li><%= link_to "Search Recipes",  query_many_path(:recipes)%></li>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </nav><!-- /navbar -->


<div id="user_nav">
  <% if user_signed_in? %>
  	Signed in as <%= current_user.email %>. Not you? <%= link_to "Sign
  	out", destroy_user_session_path, :method => :delete %>
  <% else %>
  	<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</div>

 <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
 <% end %>

<%= yield %>

<div id="main">
	
<%=yield%>



<div id="options">
	<%= form_tag(controller: "recipes", action: "form", method: "psot") do%>
	<h4>Select Ingredients:</h4>
	  <% @meat.each do |o| %>
	  		<p style="display:inline">
	  			<%file = image_tag(o+".png")%>
	  			 <%=file%>
 		 		<input name="name[]" class="<%=o%>" type="checkbox" value="<%=o%>" />
 		 	</p>
 		<%end%>
 		<hr>
 		<% @vegetables.each do |o| %>
	  			<%file = image_tag(o+".png")%>
	  			<%=file%>
 		 		<input name="name[]" class="<%=o%>" type="checkbox" value="<%=o%>" /> 
 		<%end%>
 		<hr>
 		<% @spices.each do |o| %>
	  			<%file = image_tag(o+".png")%>
	  			<%=file%>
 		 		<input name="name[]" class="<%=o%>" type="checkbox" value="<%=o%>" />
 		<%end%>

 		<hr>
 		<% @misc.each do |o| %>
	  			<%file = image_tag(o+".png")%>
	  			<%=file%>
 		 		<input name="name[]" class="<%=o%>" type="checkbox" value="<%=o%>" />
 		<%end%>

 		<br>
	  <%= submit_tag("Find Me Recipes", class:"btn btn-success") %>
	<% end %>
</div>
</div>